spring.application.name=auth-service
server.port=8081

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/

spring.datasource.url=${DB_URL_AUTH:jdbc:mysql://localhost:3306/fund_matrix_auth?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

jwt.secret=${JWT_SECRET:mySecretKeyForJWTSigningInAuthServiceLongerThan256BitsSoWeCanUseItWithHS256Algorithm}
jwt.expiration=${JWT_EXPIRATION:86400000}

logging.level.com.fundmatrix=INFO
